### PR TITLE
[cpp] Add Seidel solver.

### LINKED ISSUE #156: [CPP] Limit on the sd variable
Dear @hungpham2511,

is there a rationale for the hardcoded values
```c++
  x << 0, 100;
  x_next << 0, 1;
```
at line https://github.com/hungpham2511/toppra/blob/ec723091a717373413d5747d6c1e56d57a646fa1/cpp/src/toppra/algorithm.cpp#L40 ?

I couldn't find such a limit in the Python implementation.

### PR DESCRIPTION
**Pull request by jmirabel**
Fixes #156 and #109.

Checklists:
- [x] Update HISTORY.md with a single line describing this PR

### CODE REVIEW

**Comment by jmirabel** [comment]
I haven't exposed my functions to Python. I know it is a pity to have two implementations of the same thing but I won't have time to work on this now. I leave this to future work.

**Comment by hungpham2511** [comment]
Hi Joseph, thanks for the PR! I have been wanting to implement/someone to implement this feature for quite a while. 

Just curious, what motivates you to implement this feature? Is it because of concerns about solve time?

**Comment by jmirabel** [comment]
Resolution time is only a bonus. I have some numerical issues which I hope to solve with Seidel solver. Let's see.

**Comment by hungpham2511** [comment]
I see. What kind of fail cases did you have? 

In my experience, solvers are only part of the picture. Scaling, etc.. are also important factors to consider.

**Review by hungpham2511 — APPROVED** [review]
LGTM! Thanks for the work.

**Pull request merged**
